import { useEffect, useState } from "react";
import { ArrowUpRight, CheckCircle2, Clock3, FolderKanban, Users, Video } from "lucide-react";
import api from "../api/client.js";

const metric = (label, value, note, Icon, tone) => <article className={`metric-card ${tone}`}><div><p>{label}</p><strong>{value}</strong><small>{note}</small></div><span className="metric-icon"><Icon size={21} /></span></article>;

export default function DashboardPage() {
  const [data, setData] = useState({ teams: [], meetings: [], tasks: [], meetingAnalytics: null, taskAnalytics: null });
  useEffect(() => { Promise.allSettled([api.get("/teams"), api.get("/meetings"), api.get("/tasks"), api.get("/meetings/analytics"), api.get("/tasks/analytics")]).then((results) => { const value = (i, key) => results[i].status === "fulfilled" ? results[i].value.data[key] : null; setData({ teams: value(0, "teams") || [], meetings: value(1, "meetings") || [], tasks: value(2, "tasks") || [], meetingAnalytics: value(3, "analytics"), taskAnalytics: value(4, "analytics") }); }); }, []);
  const upcoming = data.meetings.filter((m) => m.status === "SCHEDULED").slice(0, 4);
  const activeTasks = data.tasks.filter((t) => t.status !== "DONE").slice(0, 5);
  return <><div className="page-heading"><div><h2>Workspace overview</h2><p>Here is what is moving across your teams today.</p></div></div><div className="metrics-grid">{metric("Teams", data.teams.length, "Active workspaces", Users, "blue")}{metric("Meetings", data.meetingAnalytics?.totalMeetings ?? data.meetings.length, `${data.meetingAnalytics?.ongoingMeetings ?? 0} currently ongoing`, Video, "purple")}{metric("Open tasks", data.tasks.filter((t) => t.status !== "DONE").length, "Across all boards", FolderKanban, "orange")}{metric("Completed work", data.taskAnalytics?.completedTasks ?? data.tasks.filter((t) => t.status === "DONE").length, "Tasks marked done", CheckCircle2, "green")}</div><div className="dashboard-grid"><section className="panel"><div className="panel-title"><div><h3>Upcoming meetings</h3><p>Scheduled calls across your workspace</p></div><Video size={20} /></div>{upcoming.length ? <div className="list">{upcoming.map((meeting) => <div className="list-row" key={meeting._id}><span className="meeting-date"><Clock3 size={15} />{new Date(meeting.scheduledAt).toLocaleDateString()}</span><div><strong>{meeting.title}</strong><small>{meeting.team?.name || "No team"}</small></div><ArrowUpRight size={18} /></div>)}</div> : <div className="empty-state">No upcoming meetings yet.</div>}</section><section className="panel"><div className="panel-title"><div><h3>Priority tasks</h3><p>Work that still needs attention</p></div><FolderKanban size={20} /></div>{activeTasks.length ? <div className="list">{activeTasks.map((task) => <div className="list-row" key={task._id}><span className={`status-dot ${task.priority?.toLowerCase()}`} /><div><strong>{task.title}</strong><small>{task.team?.name || "Workspace task"} · {task.status?.replace("_", " ")}</small></div><span className="priority-pill">{task.priority}</span></div>)}</div> : <div className="empty-state">Your task board is clear.</div>}</section></div></>;
}
