import { useEffect, useState } from "react";
import { CalendarPlus, Play, Users } from "lucide-react";
import api, { getApiError } from "../api/client.js";
import Modal from "../components/Modal.jsx";
import { useAuth } from "../context/AuthContext.jsx";

export default function MeetingsPage() {
 const [meetings,setMeetings]=useState([]),[teams,setTeams]=useState([]),[show,setShow]=useState(false),[error,setError]=useState(""); const [form,setForm]=useState({title:"",description:"",team:"",scheduledAt:""}); const {user}=useAuth(); const canManage=["MANAGER","ADMIN","SUPER_ADMIN"].includes(user?.role);
 const load=async()=>{const [m,t]=await Promise.all([api.get("/meetings"),api.get("/teams")]);setMeetings(m.data.meetings||[]);setTeams(t.data.teams||[])}; useEffect(()=>{load()},[]);
 const create=async(e)=>{e.preventDefault();try{await api.post("/meetings",{...form,scheduledAt:new Date(form.scheduledAt).toISOString()});setShow(false);load()}catch(err){setError(getApiError(err))}};
 const join=async(id)=>{await api.post(`/meetings/${id}/join`);load()};
 return <><div className="page-heading"><div><h2>Meetings</h2><p>Plan, host, and review collaboration sessions.</p></div>{canManage&&<button className="primary-button" onClick={()=>setShow(true)}><CalendarPlus size={18}/>Schedule meeting</button>}</div><div className="meeting-list">{meetings.map(m=><article className="meeting-card" key={m._id}><div className="meeting-time"><strong>{new Date(m.scheduledAt).toLocaleDateString(undefined,{month:"short",day:"numeric"})}</strong><span>{new Date(m.scheduledAt).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</span></div><div className="meeting-details"><div className="tag-row"><span className={`tag ${m.status?.toLowerCase()}`}>{m.status}</span><span>{m.team?.name||"Team"}</span></div><h3>{m.title}</h3><p>{m.description||"No meeting description."}</p><small><Users size={14}/>{m.participants?.length||0} participants</small></div><button className="secondary-button" onClick={()=>join(m._id)}><Play size={16}/>{m.status==="ONGOING"?"Join now":"Join"}</button></article>)}{!meetings.length&&<div className="empty-state wide">No meetings scheduled.</div>}</div>{show&&<Modal title="Schedule a meeting" onClose={()=>setShow(false)}><form className="modal-form" onSubmit={create}><label>Meeting title<input required minLength="3" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Team<select required value={form.team} onChange={e=>setForm({...form,team:e.target.value})}><option value="">Select a team</option>{teams.map(t=><option value={t._id} key={t._id}>{t.name}</option>)}</select></label><label>Date and time<input required type="datetime-local" value={form.scheduledAt} onChange={e=>setForm({...form,scheduledAt:e.target.value})}/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{error&&<p className="form-error">{error}</p>}<button className="primary-button">Schedule meeting</button></form></Modal>}</>;
}
